### ISSUE TITLE
Export HtmlFileConfiguration interface

### ISSUE THREAD

**Issue by misterquestions** [craftamap/esbuild-plugin-html#27]
Hey there,

I recently found this project and it's really awesome, I'd be great to have these typings exported, even if the configuration for esbuild is plain js, when using JSDoc comments and defining @type it's helpful.

Example usage: 

```JS
/**
 * Build all the configurations for the esbuild to make our resource work
 *
 * @type { Array<import('@craftamap/esbuild-plugin-html').HtmlFileConfiguration> }
 **/
const viewOptions = views.map((viewFile) => {
  const viewFile = join(viewsPath, viewFile);
  const viewName = basename(viewFile);

  return {
    ...
  };
});
```

**Comment by craftamap** [comment]
Hey there!

Looks like I missed to do this. A fix will be released soon :)

**Comment by misterquestions** [comment]
Alright, thank you very much! 

Works just fine, really appreciate it.
