### ISSUE TITLE
“entryNames" makes fail to inject entryPoints

### ISSUE THREAD

**Issue by fifv** [craftamap/esbuild-plugin-html#29]
When I add entryNames, the output html don’t contain any reference to scripts or css

I tried to write a minimum demo:

```bash
|-src/
|--index.js
|-esbuild.js
```

`esbuild.js` :

```jsx
const { htmlPlugin } = require('@craftamap/esbuild-plugin-html');
require('esbuild').build({
    entryPoints: ['src/index.js'],
    entryNames:'[name]-[hash]',
    bundle: true,
    outdir: 'dist',
    metafile: true,
    plugins: [
        htmlPlugin({
            files: [
                {
                    entryPoints: [
                        'src/index.js',
                    ],
                    filename: 'index.html',
                }
            ],
        }),
    ],
})
```

I run node `esbuild.js` then get the output /dist/index.html:

```html
<!DOCTYPE html><html><head>
    <meta charset="utf-8">
  </head>
  <body>
  

</body></html>
```

seems that the index.js fails to be injected into html

If I comment out `entryNames:'[name]-[hash]',`  then output is correct:

```html
<!DOCTYPE html><html><head>
    <meta charset="utf-8">
  </head>
  <body>
  

<script src="index.js" defer=""></script></body></html>
```

Here is my system info:

- node: v16.13.1
- esbuild: 0.14.34
- @craftamap/esbuild-plugin-html: 0.3.2
- windows10 home:  21H2 19044.1586

**Comment by fifv** [comment]
I clone the repository, change the line:204, build and replace the one in node_modules then the html output seems correct

```jsx
for (const entrypoint of collectedEntrypoints) {
                        if (!entrypoint) {
                            throw new Error(`Found no match for ${htmlFileConfiguration.entryPoints}`)
                        }
                        let relatedOutputFiles
                        if (htmlFileConfiguration.findRelatedOutputFiles) {
                            /* - */  // relatedOutputFiles = findRelatedOutputFiles(entrypoint, result.metafile, build.initialOptions.entryNames)
                            /* + */     relatedOutputFiles = [entrypoint]
                        } else {
                            relatedOutputFiles = [entrypoint]
                        }

                        collectedOutputFiles = [...collectedOutputFiles, ...relatedOutputFiles]
                    }
```

But I’m beginner to esbuild, I don’t understand how plugins works and don’t know why changing like this works. So hope someone knows to fix this.

**Comment by craftamap** [comment]
Thanks for reporting this, I'm gonna take a look at this later :)

**Comment by tcchau** [comment]
> const { htmlPlugin } = require('@craftamap/esbuild-plugin-html');
> require('esbuild').build({
>     entryPoints: ['src/index.js'],
>     entryNames:'[name]-[hash]',

The key seems to be the use of a hash in the file name; if the hash is not used, i.e. output is index/app.js, then the injection will occur correctly. I've run into this myself but haven't had time to debug.

**Comment by craftamap** [comment]
Looks like this is related to Windows, as it seems to work on Linux, but not on Windows. I'm gonna work on a fix. :)

**Comment by fifv** [comment]
It works now!😀
Thanks for your effort!
