### ISSUE TITLE
Use esbuild to build the project

### ISSUE THREAD

**Issue by craftamap** [craftamap/esbuild-plugin-html#3]
Kinda embarrassing to use `tsc`, tbh.

**Comment by TurtIeSocks** [comment]
[Esbuild doesn't support outputting type declaration files](https://esbuild.github.io/content-types/#typescript-caveats) so this might not be feasible unless you want to manually maintain them.

**Comment by craftamap** [comment]
Yeah, it's a shame. :/

**Comment by mdedys** [comment]
In the process of ditching webpack for esbuild and taking a look at this plugin (taking for building this), but I would argue that using tsc for this plugin is perfectly fine and probably better. esbuild is meant as a bundler and when creating an NPM you don't need to bundle your code. Running it through typescript compiler is more then sufficient. You can even setup your build step to output both CJS and ESM with tsc alone.

**Comment by craftamap** [comment]
@mdedys thanks for the input :)
