### ISSUE TITLE
Favicon does not include publicPath

### ISSUE THREAD

**Issue by Eomm** [craftamap/esbuild-plugin-html#36]
When we set the `favicon` option, the `publicPath` is ignored here:

https://github.com/craftamap/esbuild-plugin-html/blob/1a141e36618c1601646ecf8f34bd3aea64cc412a/lib/cjs/index.js#L216

Example:

```js
const esbuild = require('esbuild');
const { htmlPlugin } = require('@craftamap/esbuild-plugin-html');

const htmlPluginConfig = [
   {
     entryPoints: ['src/main.html'],
     filename: 'index.html',
     scriptLoading: 'module',
     favicon: 'assets/images/favicon2020.ico' <== path to favicon 
   },
];

esbuild.build({
  bundle: true,
  outdir,
  entryNames: '[name]-[hash]',
  entryPoints: ['./src/main.html'],
  plugins: [htmlPluginConfig], 
  target: TARGET,
  format: 'esm',
  publicPath: '/foo',
}).catch(() => process.exit(1))
```

**Comment by craftamap** [comment]
Thanks for reporting :) 

Just to make sure that I get this correctly, in the HTML file the favicon path should be prefixed with the public path?

**Comment by Eomm** [comment]
> Just to make sure that I get this correctly, in the HTML file the favicon path should be prefixed with the public path?

Yes, I would expect that but it is not happening
