### ISSUE TITLE
Specify specific assets to be inlined (instead of inlining everything)

### ISSUE THREAD

**Issue by cha0s** [craftamap/esbuild-plugin-html#51]
It is currently only possible to inline nothing, everything, or all of a given class (script, style). It would be better if it were possible to pass in e.g. a regex to specify specific assets to be inlined instead of the current all-or-nothing approach.

**Comment by craftamap** [comment]
thanks for the suggestion - I guess we could also support accepting a function that allows custom behavior here.

**Comment by craftamap** [comment]
@cha0s you might want to check out the linked PR to see if this would solve your needs :) https://github.com/craftamap/esbuild-plugin-html/pull/52
