### ISSUE TITLE
HTML file not present when using esbuild's ctx.serve after accesing localhost:8000

### ISSUE THREAD

**Issue by pardoman** [craftamap/esbuild-plugin-html#53]
With:
- esbuild version 0.19.10
- yarn 4.0.2

This is probably a configuration issue, but I can't seem to figure out how to make it work.

I have setup a build script to generate the HTML just fine using `esbuild.build(config)`

Now I'm trying to make a dev script using `esbuild.context` and `ctx.serve` as follows:

```mjs
// File: config/config.mjs
import fs from "fs";
import * as esbuild from 'esbuild'
import { htmlPlugin } from "@craftamap/esbuild-plugin-html";

const HTML_TEMPLATE_STRING = fs.readFileSync("resources/index.html", { encoding: 'utf8', flag: 'r' });

export const config = {
  entryPoints: ['src/app.tsx'],
  bundle: true,
  metafile: true, // required by htmlPlugin
  outdir: 'dist/',
  tsconfig: "tsconfig.json",
  assetNames: 'assets/[ext]/[name]-[hash]',
  loader: { '.png': 'file' },
  plugins: [
    htmlPlugin({
      files: [
        {
          filename: "index.html",
          entryPoints: ['src/app.tsx'],
          htmlTemplate: HTML_TEMPLATE_STRING
        }
      ]
    })
  ]
}

let ctx = await esbuild.context(config);
let { host, port } = await ctx.serve()
console.log(`Serving on ${host} port ${port}`);
```

Which I'm calling from a `package.json` script: 

```json
{
  "scripts": {
    "start": "node ./config/config.mjs",
  }
}
```

Using `yarn start` 
![image](https://github.com/craftamap/esbuild-plugin-html/assets/2985436/4b47e6ad-8604-4649-beaa-5ce927ef17d9)

and navigating to localhost:8000
![image](https://github.com/craftamap/esbuild-plugin-html/assets/2985436/3a60ff20-9aa0-4328-b829-b0599272b43f)

However, the output folder DOES contain the HTML:
![image](https://github.com/craftamap/esbuild-plugin-html/assets/2985436/0dfd141e-2dca-4d93-9f9f-6be22c156f73)

And the content of the file is as expected:
```html
<!DOCTYPE html><html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
    body {
        margin: 0;
    }
    </style>
</head>
<body>
    <div id="root"></div>

<script src="app.js" defer=""></script></body></html>
```

Any idea what am I missing to make the HTML available on localhost:8000?

**Comment by ItsMeLeonardo** [comment]
You could try specifying the serverdir like this

```js
const { host, port } = await ctx.serve({
  servedir: "dist",
});
```

maybe that will fix it

**Comment by pardoman** [comment]
@ItsMeLeonardo yup, that did it. Thank you!

**Comment by craftamap** [comment]
Thanks @ItsMeLeonardo for helping out here! That is indeed the same thing that I would recommend. :)
