### ISSUE TITLE
Replace lodash.template with template from lodash to avoid dependabot alerts

### ISSUE THREAD

**Issue by elrob** [craftamap/esbuild-plugin-html#57]
https://github.com/lodash/lodash/issues/5851

https://github.com/advisories/GHSA-35jh-r3h4-6jhm

Should be as simple as replacing the package to lodash or lodash-es and changing the import.
https://github.com/craftamap/esbuild-plugin-html/blob/8aab0e2e4ed9006f91febf7dbf4c77b388a467a2/package.json#L37

**Comment by craftamap** [comment]
Thanks @severian for fixing this in https://github.com/craftamap/esbuild-plugin-html/pull/59  :^)

**Comment by elrob** [comment]
Thank you!

**Comment by elrob** [comment]
@craftamap Are you able to publish a new release including the lodash dependency change?

**Comment by craftamap** [comment]
done, v0.7.0 got released:)

**Comment by elrob** [comment]
Thank you!

**Comment by jacwright** [comment]
0.7.0 is outputting the template tags in my HTML. Is anyone else seeing this?

Example:
```html
<link.../>
&lt% if (myLogic) { %&gt;
<script>...</script>
&lt% } %&gt;
```
0.6.1 works fine.

**Comment by elrob** [comment]
I didn't see any issues but that's probably because I don't have any templating, just a static HTML snippet.
